#-------------------------------
# General Site Settings
title: Mesheritage
logo: logo.png # You can add own logo.
description: Mesheritage website


#-------------------------------
# Author Settings
author:
  name: Mesheritage
  image: logo.png
  say-hello: A new look at the past
  bio: We are a group of researcher working on different ways to replicate lost heritage. With 3D models and virutal environments, we offer a new insight on treasure that can no longer be seen 


#-------------------------------
# Contact links
twitter: https://twitter.com/mesheritage # Add your Twitter handle
facebook: https://www.facebook.com/MESHeritage # Add your Facebook handle
instagram: https://instagram.com/ # Add your Instagram handle
pinterest: https://pinterest.com/ # Add your Pinterest handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: Mesheritage # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: true # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: pmr_max # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e